DROP PROCEDURE `PLAYER_UPDATE`;
DELIMITER $$
	CREATE PROCEDURE
		`PLAYER_UPDATE`
		(IN `_steamid` VARCHAR(32), 
			IN `_boxes_open` INT,
			IN `_boxes_specials_open` INT,
			IN `_counter_bh` INT,
			IN `_counter_commands` INT,
			IN `_counter_lvp` INT,
			IN `_counter_messages` INT,
			IN `_counter_mvp` INT,
			IN `_counter_suicide` INT,
			IN `_counter_witch_disturb` INT,
			IN `_friends_above` INT,
			IN `_friends_adrenaline_given` INT,
			IN `_friends_cured` INT,
			IN `_friends_damage` INT,
			IN `_friends_incapped` INT,
			IN `_friends_killed` INT,
			IN `_friends_pills_given` INT,
			IN `_friends_protected` INT,
			IN `_friends_rescued` INT,
			IN `_friends_revived` INT,
			IN `_gift_taken` INT,
			IN `_headshots` INT,
			IN `_infected_let_in_safehouse` INT,
			IN `_kill_boomers` INT,
			IN `_kill_bosses` INT,
			IN `_kill_chargers` INT,
			IN `_kill_hunters` INT,
			IN `_kill_jockeys` INT,
			IN `_kill_smookers` INT,
			IN `_kill_spitters` INT,
			IN `_kill_tanks` INT,
			IN `_kill_tanks_without_deaths` INT,
			IN `_kill_witches` INT,
			IN `_kill_zombies` INT,
			IN `_killed_by_boomer` INT,
			IN `_killed_by_charger` INT,
			IN `_killed_by_hunter` INT,
			IN `_killed_by_jockey` INT,
			IN `_killed_by_smooker` INT,
			IN `_killed_by_spitter` INT,
			IN `_killed_by_tank` INT,
			IN `_killed_by_witch` INT,
			IN `_left4dead` INT,
			IN `_melee_kills` INT,
			IN `_playtime` INT,
			IN `_points` INT,
			IN `_points_gift` INT,
			IN `_points_lost` INT,
			IN `_points_vip` INT,
			IN `_rounds` INT,
			IN `_rounds_all_survive` INT,
			IN `_rounds_failed` INT,
			IN `_rounds_successful` INT,
			IN `_self_adrenaline` INT,
			IN `_self_cured` INT,
			IN `_self_pills` INT,
			IN `_server_join` INT,
			IN `_server_left` INT,
			IN `_spokentime` INT
		)
		MODIFIES SQL DATA
		COMMENT 'Update info from server l4d2'
	BEGIN
		UPDATE players
		SET
			boxes_open = boxes_open + _boxes_open,
			boxes_specials_open = boxes_specials_open + _boxes_specials_open,
			counter_bh = counter_bh + _counter_bh,
			counter_commands = counter_commands + _counter_commands,
			counter_lvp = counter_lvp + _counter_lvp,
			counter_messages = counter_messages + _counter_messages,
			counter_mvp = counter_mvp + _counter_mvp,
			counter_suicide = counter_suicide + _counter_suicide,
			counter_witch_disturb = counter_witch_disturb + _counter_witch_disturb,
			friends_above = friends_above + _friends_above,
			friends_adrenaline_given = friends_adrenaline_given + _friends_adrenaline_given,
			friends_cured = friends_cured + _friends_cured,
			friends_damage = friends_damage + _friends_damage,
			friends_incapped = friends_incapped + _friends_incapped,
			friends_killed = friends_killed + _friends_killed,
			friends_pills_given = friends_pills_given + _friends_pills_given,
			friends_protected = friends_protected + _friends_protected,
			friends_rescued = friends_rescued + _friends_rescued,
			friends_revived = friends_revived + _friends_revived,
			gift_taken = gift_taken + _gift_taken,
			headshots = headshots + _headshots,
			infected_let_in_safehouse = infected_let_in_safehouse + _infected_let_in_safehouse,
			kill_boomers = kill_boomers + _kill_boomers,
			kill_bosses = kill_bosses + _kill_bosses,
			kill_chargers = kill_chargers + _kill_chargers,
			kill_hunters = kill_hunters + _kill_hunters,
			kill_jockeys = kill_jockeys + _kill_jockeys,
			kill_smookers = kill_smookers + _kill_smookers,
			kill_spitters = kill_spitters + _kill_spitters,
			kill_tanks = kill_tanks + _kill_tanks,
			kill_tanks_without_deaths = kill_tanks_without_deaths + _kill_tanks_without_deaths,
			kill_witches = kill_witches + _kill_witches,
			kill_zombies = kill_zombies + _kill_zombies,
			killed_by_boomer = killed_by_boomer + _killed_by_boomer,
			killed_by_charger = killed_by_charger + _killed_by_charger,
			killed_by_hunter = killed_by_hunter + _killed_by_hunter,
			killed_by_jockey = killed_by_jockey + _killed_by_jockey,
			killed_by_smooker = killed_by_smooker + _killed_by_smooker,
			killed_by_spitter = killed_by_spitter + _killed_by_spitter,
			killed_by_tank = killed_by_tank + _killed_by_tank,
			killed_by_witch = killed_by_witch + _killed_by_witch,
			left4dead = left4dead + _left4dead,
			melee_kills = melee_kills + _melee_kills,
			playtime = playtime + _playtime,
			points = points + _points,
			points_gift = points_gift + _points_gift,
			points_lost = points_lost + _points_lost,
			points_vip = points_vip + _points_vip,
			rounds = rounds + _rounds,
			rounds_all_survive = rounds_all_survive + _rounds_all_survive,
			rounds_failed = rounds_failed + _rounds_failed,
			rounds_successful = rounds_successful + _rounds_successful,
			self_adrenaline = self_adrenaline + _self_adrenaline,
			self_cured = self_cured + _self_cured,
			self_pills = self_pills + _self_pills,
			server_join = server_join + _server_join,
			server_left = server_left + _server_left,
			spokentime = spokentime + _spokentime
		WHERE steamid = SteamIdTo64(_steamid);
	END$$
DELIMITER ;